name = 'softhub'
main = 'src/index.ts'
compatibility_date = '2024-03-05'

[vars]
MSAL_TENANT_ID = "42914ade-3afa-4add-b06f-11c68f45a379"
MSAL_CLIENT_ID = "da147183-fe1b-486f-a3e5-a41fdd9cd66e"
DOMINIO_INSTITUCIONAL = "unieuro.com.br"
BOOTSTRAP_ADMIN_EMAIL = "mateus099803@unieuro.com.br"
JWT_SECRET = "softhub-secret-padrao-trocar-em-producao"


[[d1_databases]]
binding = 'DB'
database_name = 'softhub_db'
database_id = 'e61486a2-7323-49d8-9e4a-a0543892b1da'

[[kv_namespaces]]
binding = "SESSOES_QR"
id = "4e8bff2b06d644b79749e9127e35f963"